export { ReactComponent as LogoIcon } from './img/logo.svg';
export { ReactComponent as FacebookIcon } from './img/faceboock.svg';
export { ReactComponent as InstagramIcon } from './img/instagram.svg';
export { ReactComponent as TelegramIcon } from './img/telegram.svg';
export { ReactComponent as TicTocIcon } from './img/tik-tok.svg';
export { ReactComponent as ArrowIcon } from './img/arrow.svg';
export { ReactComponent as CakeIcon } from './img/cake.svg';
export { ReactComponent as CupIcon } from './img/cup.svg';
export { ReactComponent as BagIcon } from './img/handbag.svg';
export { ReactComponent as FragmentIcon } from './img/fragment.svg';
export { ReactComponent as OneStarIcon } from './img/oneStar.svg';
export { ReactComponent as PlusIcon } from './img/plus.svg';
export { ReactComponent as LineIcon } from './img/line.svg';
export { ReactComponent as PhotoIcon } from './img/photo.svg';
export { ReactComponent as ComfortIcon } from './img/comfort.svg';
export { ReactComponent as DevelopmentIcon } from './img/development.svg';
export { ReactComponent as FreeIcon } from './img/freeIcon.svg';
export { ReactComponent as ProspectsIcon } from './img/prospects.svg';
export { ReactComponent as BurstStarIcon } from './img/burst-star.svg';
export { ReactComponent as ArrowButtonIcon } from './img/arrow-button.svg';

export { Accordion } from './Accordion/Accordion';
export { LinkComponent } from './LinkComponent/LinkComponent';
export { Button } from './Button/Button';
export { navBtnList } from './config/constants';
export { coursesList } from './config/constants';
export { contacts } from './config/constants';
export { titleCoursesList } from './config/constants';
export { teachersList } from './config/constants';
export { coursePageText } from './config/constants';
export { TeacherCard } from './TeacherCard/TeacherCard';
